export const tutorialInteractables = [
  {
    id: "miller",
    type: "npc",
    mapId: "tutorial-lobby",
    x: 5,
    y: 5,
    sceneId: "security-room",
    prompt: "Hablar con Miller",
  },
  {
    id: "basement-door",
    type: "object",
    mapId: "tutorial-lobby",
    x: 11,
    y: 7,
    sceneId: "basement-enter",
    prompt: "Bajar al sotano",
  },
  {
    id: "to-gallery",
    type: "exit",
    mapId: "tutorial-lobby",
    x: 13,
    y: 5,
    targetMapId: "tutorial-gallery",
    spawn: "fromLobby",
    prompt: "Ir a la sala de exhibicion",
  },
  {
    id: "sarah",
    type: "npc",
    mapId: "tutorial-gallery",
    x: 10,
    y: 4,
    sceneId: "lab-room",
    prompt: "Hablar con Sarah",
  },
  {
    id: "exhibit-case",
    type: "object",
    mapId: "tutorial-gallery",
    x: 7,
    y: 4,
    sceneId: "exhibit-case",
    prompt: "Inspeccionar vitrina",
  },
  {
    id: "back-to-lobby",
    type: "exit",
    mapId: "tutorial-gallery",
    x: 3,
    y: 8,
    targetMapId: "tutorial-lobby",
    spawn: "fromGallery",
    prompt: "Volver al vestibulo",
  },
];
