export const tutorialMaps = [
  {
    id: "tutorial-lobby",
    label: "Vestibulo",
    location: "hall",
    tileset: "/sprites/Room_Builder_free_16x16.png",
    tileSize: 16,
    layout: [
      "################",
      "#===..tt....pp.#",
      "#=..###..cc.pp.#",
      "#=..#....cc.pp.#",
      "#=..........pp.#",
      "#=..cc..cc..pp.#",
      "#=....###..ppp.#",
      "#=..rr.....Dpp.#",
      "#=..rr....pppp.#",
      "################",
    ],
    solidTiles: ["#", "r", "c"],
    spawnPoints: {
      default: { x: 2, y: 2 },
      fromGallery: { x: 13, y: 5 },
    },
  },
  {
    id: "tutorial-gallery",
    label: "Sala de exhibicion",
    location: "exhibit",
    tileset: "/sprites/Room_Builder_free_16x16.png",
    tileSize: 16,
    layout: [
      "################",
      "#~~~..ccc..pp..#",
      "#~~..######.pp.#",
      "#~..#..aa..#p..#",
      "#~..#.Eaa..#p..#",
      "#~..#..aa..#p..#",
      "#~~..######.pp.#",
      "#~~~....dd..pp.#",
      "#..D...dd..pp..#",
      "################",
    ],
    solidTiles: ["#", "a", "d"],
    spawnPoints: {
      default: { x: 2, y: 2 },
      fromLobby: { x: 1, y: 8 },
    },
  },
];
